version: "3"
services:
  michaaibot:
    image: michaaiai/michaaibot:master
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - ./token.txt:/ItsMichaAIBot
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379"
