version: "3"
services:
  michaaibot:
    image: michaaiai/michaaibot:master
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - ./token.txt:/token.txt
    depends_on:
      - redis
      - redis1
  redis:
    image: redis
    ports:
      - "6379"
  redis1:
    image: redis
    ports:
      - "6380"
