version: "3"
services:
  michaaibot:
    image: michaaiai/michaaibot:master
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - ./token.txt:/token.txt
    depends_on:
      - redis
      - redis1

  redis:
    image: redis
    ports:
      - "6379"

  redis1:
    image: redis:alpine
    ports:
      - "6380"
    hostname: redis1
    domainname: redis1
    command: redis-server --port 6380
